blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentation
    url: https://github.com/cjpritchard/home-ops/tree/main/docs
    about: Check the docs folder for setup guides and troubleshooting
  - name: ğŸš€ Taskfile Commands
    url: /docs
    about: Check the docs folder for setup guides and troubleshooting
  - name: ğŸš€ Taskfile Commands
    url: /Taskfile.yaml
    about: View available task commands for cluster management
